### ISSUE TITLE
1.3.17 Compatibility

### ISSUE THREAD

**Issue by coltonb** [cdaragorn/Ui-Info-Suite#11]
Smapi flags this mod as incompatible with the advent of SDV 1.3.17

Specifically from my testing, the problem seems to stem from the reference of `Game1.player.toolBeingUpgraded`, which has likely been made obsolete from the recent bugfix:

- Fixed farmhand tools disappearing after logging out while being upgraded

**Comment by Zamiell** [comment]
Annosz has graciously volunteered to start maintaining this project: https://github.com/Annosz/UIInfoSuite2

The current version of the fork does work on 1.3.17.
