### ISSUE TITLE
[Suggestion] Persistent configuration

### ISSUE THREAD

**Issue by williamjcm** [cdaragorn/Ui-Info-Suite#15]
I use both UI Info Suite and NPC Map Locations, and I find the latter's NPC tracking to be better.

However, every time I launch the game, I need to disable UI Info Suite's "show NPCs on map" feature.

Of course, that's not the only mod option that's not saved.

I'd like to suggest the addition of variables in `config.json` to save the whole mod configuration.

**Comment by cdaragorn** [comment]
This was implemented the day the mod was first created. It saves those settings per character you play in a file named "characterName_moddata.xml"
