### ISSUE TITLE
Is this repository still maintained? Is this mod still open source?

### ISSUE THREAD

**Issue by ThomasOwens** [cdaragorn/Ui-Info-Suite#5]
This is one of the few SDV mods that I use, and I was going to work on PRs for 1.3 this weekend. I notice that there is a beta release on Nexus Mods for 1.3, though. I don't see anything in this repository indicating it. It seems like what's on Nexus Mods aren't the same. Is this mod still open source? If so, is Github still where development happens or has it moved somewhere else?

**Comment by cdaragorn** [comment]
Yes, sorry I let it get a little out of date. I've uploaded my latest changes for the 1.3 beta onto a branch for now.
